// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import ftp "github.com/molotovtv/go-ftp"
import mock "github.com/stretchr/testify/mock"
import time "time"

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields: addr
func (_m *Dialer) Dial(addr string) (ftp.ServerConnexion, error) {
	ret := _m.Called(addr)

	var r0 ftp.ServerConnexion
	if rf, ok := ret.Get(0).(func(string) ftp.ServerConnexion); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ftp.ServerConnexion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DialTimeout provides a mock function with given fields: addr, timeout
func (_m *Dialer) DialTimeout(addr string, timeout time.Duration) (ftp.ServerConnexion, error) {
	ret := _m.Called(addr, timeout)

	var r0 ftp.ServerConnexion
	if rf, ok := ret.Get(0).(func(string, time.Duration) ftp.ServerConnexion); ok {
		r0 = rf(addr, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ftp.ServerConnexion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(addr, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
